// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykldcfioxyarulwzaxua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrbGRjZmlveHlhcnVsd3pheHVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMDMzNzYsImV4cCI6MjA2NzU3OTM3Nn0.FB6ksfHvgkU6IiFXVlW3SkH73QdL0TVnhxOnWSFvJJA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});